Sprint5/step1
Danon12n/DanonReactBurger pull request #9
Opened 2022-12-21 01:10 UTC by Danon12n

2022-12-21 06:37 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец!**

- Теперь в приложении есть лента заказа;
- Используются веб-сокеты;

### **Но есть замечания, которые нужно исправить:**

- По макету, в хедере иконка тоже должна быть выделена белым цветом - https://yadi.sk/d/HjyJwEEzzXajHA;

- Думаю тут лучше разбить 1 большой столбик, на 3 маленьких, по 5 элементов - https://yadi.sk/i/-7PG8ELiF1ClmQ;

- у вас присутствует боковой скролл, нужно его убрать) - https://yadi.sk/i/-7PG8ELiF1ClmQ;

- Номер заказа должен быть отцентрирован - https://yadi.sk/d/wn4jbx9pWZpHYQ;

- Нужно исправить ошибку в консоли - https://yadi.sk/d/gK1WJEg9xig3LQ;

- Не нужно добавлять к запросу `POST /orders`, параметр токен. Токен нужно добавлять только 1 запросу связанному с сокетом - `/profile/orders`. https://yadi.sk/d/1Jv-8i7tbWH43A;

- Всем запросам где нужен пользователь, нужно добавлять хедер `authorization`. Например вот так: https://yadi.sk/d/wcoxoQi28Wnj3w.

- Если нажать на заказ https://yadi.sk/d/ywV6b_MYXNahzA, то у нас в роуте появляется не тот url - https://yadi.sk/d/d0FKS0uATZlOdA, а должен быть `/profile/orders/:id` (не забудьте что, маршрут `/profile/orders/:id` доступен только авторизированным пользователям.).

  - Также поправьте вёрстку, слишком много пустого места сверху.

### **Сделает код лучше:**

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders;

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

2022-12-21 06:37 UTC, ArslanDev666 commented on react-burger/src/services/middleware/socketMiddleware.ts
> +            if (type === wsStart) {
**Надо исправить:** 

вы не закрываете сокет соедениние, чтобы закрыть сокет соеденение, вам нужно сделать следующее: 

```js
  if (type === wsClosed) {
    socket.close();
  }
```

2022-12-21 06:37 UTC, ArslanDev666 commented on react-burger/src/utils/burger-api.ts
>          headers: {
**Надо исправить:**

к этому запросу нужно добавить `authorization` хедер со значением - `Bearer ${accessToken}`.

2022-12-21 06:37 UTC, ArslanDev666 commented on react-burger/src/utils/burger-api.ts
> +    return request(`${BURGER_API_URL}/orders?token=${accessToken?.slice(7)}`, {
**Надо исправить:**

к этому запросу не нужно добавлять параметр токен, такой параметр нужен только в сокет-запросе на получение заказов пользователя.

2022-12-21 19:25 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец!**

- Практически все замечания с прошлого ревью были исправлены;

### **Но есть 1 замечание, которое нужно исправить:**

- Маршрут `/profile/orders/:id` должен быть доступен только авторизированным пользователям.

2022-12-21 20:34 UTC, Danon12n commented
Он доступен только авторизованным пользователем...

2022-12-22 07:15 UTC, ArslanDev666 commented
> Он доступен только авторизованным пользователям...
> 
> Этот роут находится в защищенном компоненте, вероятно когда проверяли, у вас в куках остался токен, а по нему проходила авторизация

Вероятнее всего, тогда извините, проблема была на моей стороне)

2022-12-22 08:38 UTC, ArslanDev666 approved these changes
## Code Review

Здравствуйте!

### **Работа принята, удачи в дальнейшем обучении!**

2022-12-22 08:39 UTC, Danon12n commented
Спасибо большое!

2022-12-23 08:32 UTC, merged